# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: PolicyRepository
      type: github
      endpoint: amsilf
      name: amsilf/sc-policy-repo
      ref: main

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            fetchDepth: 1
          - checkout: PolicyRepository
            fetchDepth: 1
          - task: Bash@3
            inputs:
              targetType: inline
              script: 'sudo apt-get -y install zip'
            displayName: 'Install zip'
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          - task: OpenPolicyAgentInstaller@0
            inputs:
              opaVersion: 'latest'
          - task: Bash@3
            inputs:
              targetType: inline
              script: 'wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O $(System.DefaultWorkingDirectory)/yq && chmod +x $(System.DefaultWorkingDirectory)/yq'
            displayName: 'Install yq'
          - task: Bash@3
            inputs:
              targetType: inline
              script: 'helm template $(System.DefaultWorkingDirectory)/sc-helm-app/sc-helm-chart/ > $(System.DefaultWorkingDirectory)/helm-chart.yml'
            displayName: 'Save Helm Chart'
          - task: Bash@3
            inputs:
              targetType: inline
              script: 'cat $(System.DefaultWorkingDirectory)/helm-chart.yml | $(System.DefaultWorkingDirectory)/yq --split-exp "(.kind | downcase)"'
            displayName: 'Helm chart to yml files'
          - task: Bash@3
            inputs:
              targetType: inline
              script: 'for f in *.yml; do yq e -o=json ${f} > ${f%.*}.json ; done;'
              workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: 'yaml to json'
      - job: Test
        dependsOn: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Bash@3
            inputs:
              targetType: inline
              script: |
                opa eval --fail-defined -i $(System.DefaultWorkingDirectory)/deployment.json -d $(System.DefaultWorkingDirectory)/sc-policy-repo/helm/availability/replica.rego 'data' > execution-result.log
            displayName: 'Execute OPA rules'
      - job: Fix
        dependsOn: Test
        condition: failed()
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
            displayName: "Install python 3.12"
          - checkout: PolicyRepository
            fetchDepth: 1
          - script: |
              ls -tlra $(System.DefaultWorkingDirectory)/
              ls -tlra $(System.DefaultWorkingDirectory)/sc-policy-repo
              ls -tlra $(System.DefaultWorkingDirectory)/sc-policy-repo/pull-request-fix/
          - script: |
              python -m pip install --upgrade pip
              pip install -r $(System.DefaultWorkingDirectory)/sc-policy-repo/pull-request-fix/requirements.txt
            displayName: 'Install dependencies'
